Added concurrent mode to utilize power of all CPUs
JayXon/Leanify pull request #67
Opened 2021-03-10 14:27 UTC by doterax

Taskflow added from sources to make AppVeyor happy
Changed c++14 to c++17 to support taskflow
Added option -c --concurrent to enable consurrent mode
Logs changed to prevent mess in it

2021-03-11 06:52 UTC, JayXon requested changes
Thanks for the pull request! Overall looks pretty good, a couple things:

### taskflow 
Could you move all the taskflow files into the `lib` directory? That's where all the third party libraries live.
Also since we are checking in code into this repo, we should remove files not needed, for example we probably don't need any of those cuda or tensor files...

### AppVeyor failures
Clang-Release; Platform: x86 you missed one of the `<ExceptionHandling>false</ExceptionHandling>` lines
Clang-Release; Platform: x64 this seems to be something else, ~~I'm not sure why it's complaining, but doesn't look like your fault, I'll see if I can fix this.~~ fixed in 7075d27

### Travis CI failures
I'm not sure why it doesn't show up in this PR, but it's building this and all failed: https://travis-ci.org/github/JayXon/Leanify/builds/762323769

### Logs
I see that you've reordered one of the logs, but that doesn't address any verbose logs, (try `-c -v`), do you have any plans for those?

2021-03-11 06:52 UTC, JayXon commented on main.cpp
> +      log = "Processing: " + filename + "\n";
nit: since with concurrent this will be printed afterwards, maybe we should print something different, Processed? Optimized? Leanified?

2021-03-11 06:52 UTC, JayXon commented on main.cpp
> +    concurrent_tasks = 1;
I'd reverse this, only call `hardware_concurrency()` if `concurrent_processing`

2021-03-11 06:52 UTC, JayXon commented on main.cpp
>  int ProcessFile(const wchar_t* file_path) {
now that this is wrapped by `EnqueueProcessFileTask`, we can change it to take `const string&` and move all the ifdef platform specific stuff to `EnqueueProcessFileTask`

2021-03-11 06:52 UTC, JayXon commented on main.cpp
> +          } else if (STRCMP(argv[i] + j + 1, "concurrent") == 0) {
I think parallel is a better name for this
https://softwareengineering.stackexchange.com/questions/190719/the-difference-between-concurrent-and-parallel-execution

2021-03-11 18:59 UTC, doterax commented on main.cpp
> +      log = "Processing: " + filename + "\n";
Word "Processed" used in parallel mode.

2021-03-11 19:00 UTC, doterax commented on main.cpp
> +    concurrent_tasks = 1;
done

2021-03-11 19:03 UTC, doterax commented on main.cpp
>  int ProcessFile(const wchar_t* file_path) {
We can't get rid of ifdefs because for windows we need wchar_t* for filenames and for the rest char* used. But I removed ftw() stuff from ProcessFile.

2021-03-11 19:04 UTC, doterax commented on main.cpp
> +          } else if (STRCMP(argv[i] + j + 1, "concurrent") == 0) {
Reworded for 'parallel' :)

2021-03-11 19:17 UTC, doterax commented
Thank you for review!

I processed all your requests. Except removing not needed files from taskflow. That because I have some plans for them.

Looks like problems with linking in Clang configurations. I will check them tomorrow on a different machine. Or if you have suggestions don't hesitate to contact me. 

Cheers :)

2021-03-12 05:58 UTC, JayXon reviewed
> I processed all your requests. Except removing not needed files from taskflow. That because I have some plans for them.

Interesting, do you mind sharing the plans?

> Looks like problems with linking in Clang configurations. I will check them tomorrow on a different machine. Or if you have suggestions don't hesitate to contact me.

Probably missing pthread?

2021-03-12 12:22 UTC, doterax commented on main.cpp
>    WideCharToMultiByte(CP_ACP, 0, file_path, -1, mbs, sizeof(mbs) - 1, nullptr, nullptr);
`WideCharToMultiByte` is needed only for non unicode console output in `ProcessFile()` when platform is WIN32. 

So as result we should have both string types for windows: `const wchar_t*` for File constructor `const char*` for console out. And I think `ProcessFile()` is the right place for `WideCharToMultiByte`

I made small changes and prevent string creation and copy for non WIN32 code.

2021-03-12 12:25 UTC, doterax commented
> Interesting, do you mind sharing the plans?

Yes, sorry.

My future plans is:
	- change the way how comandline processed
	- add more commandline options for zopflipng (for example diffirentiate number of iterations for small and big files for zopfli)
	- try playing with guetzli-cuda-opencl for JPEG (https://github.com/ianhuang-777/guetzli-cuda-opencl/tree/opencl)

2021-03-12 14:46 UTC, doterax commented
Travis CI build failed due to not full support of C++17.

https://stackoverflow.com/questions/40177006/c-variant-no-such-file-or-directory

2021-03-13 07:20 UTC, JayXon commented on main.cpp
> +#include "lib/taskflow/taskflow.hpp"
Could you address this? I don't see any new commits

2021-03-13 07:24 UTC, JayXon commented
> - try playing with guetzli-cuda-opencl for JPEG (https://github.com/ianhuang-777/guetzli-cuda-opencl/tree/opencl)

I don't think we can use guetzli in leanify, because leanify is a lossless tool but guetzli is lossy.

> Travis CI build failed due to not full support of C++17.

Sorry about this, I've already switched from travis ci to github actions, it should show up if you add a new commit.

2021-03-14 21:41 UTC, doterax commented
> Could you address this? I don't see any new commits

Yes, sorry I set up system to reproduce Clang linking issues and didn't commit before fix. And now AppVeyor works.

I had to disable optimisation for Clang, and this helped. 
Someone also faced same issue https://github.com/taskflow/taskflow/issues/300

> I don't think we can use guetzli in leanify, because leanify is a lossless tool but guetzli is lossy.

Ok, I understand. I removed all unused taksflow files.

> I've already switched from travis ci to github actions, it should show up if you add a new commit.

`gcc build on ubuntu-16.04` still not fully support C++17

Rest configurations on ubuntu are failed, and for now I have no idea how to fix them. Because problem looks same as in Clang, I tried to remove optimisation from makefile, but this is not worked.

2021-03-14 23:50 UTC, JayXon reviewed
> I had to disable optimisation for Clang, and this helped.
> Someone also faced same issue [taskflow/taskflow#300](https://github.com/taskflow/taskflow/issues/300)

Hmm I think we should figure out why it doesn't work with optimizations, right now this is a regression for using leanify on single file, at least I want to know exactly which optimization is causing this issue, do we really need to disable all the optimizations?

> `gcc build on ubuntu-16.04` still not fully support C++17

Excluded that from the matrix

> Rest configurations on ubuntu are failed, and for now I have no idea how to fix them. Because problem looks same as in Clang, I tried to remove optimisation from makefile, but this is not worked.

Try adding `-pthread` to the makefile?

2021-03-14 23:50 UTC, JayXon commented on main.cpp
> +#include <taskflow/taskflow.hpp>
one last nit: add an empty line between library header and local header

2021-03-15 08:02 UTC, doterax commented
> Try adding -pthread to the makefile?

It works. Thank you.

> Do we really need to disable all the optimizations?

I'm trying to figure out why it helps and how to preserve all optimizations.

2021-03-15 08:05 UTC, JayXon requested changes

2021-03-15 08:05 UTC, JayXon commented on Makefile
> +CFLAGS      += -Wall -Wextra -Wno-unused-parameter -Werror -O3 -msse2 -mfpmath=sse -flto -pthread
This should be added to LDFLAGS instead because it's only used during linking.

2021-03-15 18:56 UTC, doterax commented on Makefile
> +CFLAGS      += -Wall -Wextra -Wno-unused-parameter -Werror -O3 -msse2 -mfpmath=sse -flto -pthread
Fixed.

2021-03-15 19:34 UTC, doterax commented
> I'm trying to figure out why it helps and how to preserve all optimizations.

I'm working on it. Looks like rare LLVM bug. Have plans to rewrite TLS part of taskflow an enable optimisation for Clang. Also somehow SEH on Windows also involved.

2021-03-15 22:06 UTC, doterax commented on main.cpp
> +#include <taskflow/taskflow.hpp>
done

2021-03-15 22:21 UTC, doterax commented on main.cpp
> +#include "lib/taskflow/taskflow.hpp"
fixed

2021-03-15 22:26 UTC, doterax commented
Looks like everything is green now :)

2021-03-15 22:49 UTC, merged

2021-03-15 22:50 UTC, JayXon commented
Thanks!