Added --png-lossy-transparent switch.
JayXon/Leanify pull request #86
Opened 2022-10-13 18:38 UTC by doterax

Added --png-lossy-transparent switch to allow altering hidden colors of fully transparent pixels.

By default leanify behaves lossless to prevent confusion when you are working with textures with premultiplied alpha or packed lookup tables in textures.

Warning: default behavoiur has changed!

resolves JayXon/Leanify#68

2022-10-13 19:17 UTC, doterax commented
I've made some tests with real life textures from my current project. Use all of pngs.

| Test| Size (bytes)|Percent
| ------------- | -----:|-----:|
| Original      | 7 952 167 |100.00%|
| Lossless Alpha | 5 816 659 |73.14%|
| Lossy Alpha | 5 757 551 |72.40%|

So yes, lossy alpha processing is better  in terms of size. But worse in terms of unexpected behaviour for some cases.

2022-10-14 06:24 UTC, JayXon requested changes

2022-10-14 06:24 UTC, JayXon commented on main.cpp
> +  zopfly_lossy_transparent = false;
I think this should default to true, because the default should be what most people want, and in this case, the RGB in a fully transparent pixel does not affect how the image looks, only specific use cases rely on that data.
This is similar to how leanify will remove ancillary chunks in png by default.

2022-10-14 08:54 UTC, doterax commented on main.h
> +bool zopfly_lossy_transparent;
fixed typo

2022-10-14 08:55 UTC, doterax commented on main.cpp
> +  zopfly_lossy_transparent = false;
ok. and I have changed command line switch and documentation

2022-10-14 09:05 UTC, JayXon requested changes
Thanks, looks good, just one small naming issue

2022-10-14 09:05 UTC, JayXon commented on main.h
> +bool zopfli_lossy_transparent;
Could you update this to zopflipng_lossy_transparent? Because it's an option for ZopfliPNG, not zopfli

2022-10-14 09:32 UTC, doterax commented
done.


пт, 14 жовт. 2022 р. о 12:05 Sen Jiang ***@***.***> пише:

> ***@***.**** requested changes on this pull request.
>
> Thanks, looks good, just one small naming issue
> ------------------------------
>
> In main.h
> <https://github.com/JayXon/Leanify/pull/86#discussion_r995529673>:
>
> > @@ -19,7 +19,7 @@ bool is_pause;
>  int iterations;
>
>  // Allow altering hidden colors of fully transparent pixels, only for zopfli
> -bool zopfly_lossy_transparent;
> +bool zopfli_lossy_transparent;
>
> Could you update this to zopflipng_lossy_transparent? Because it's an
> option for ZopfliPNG, not zopfli
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/JayXon/Leanify/pull/86#pullrequestreview-1142084747>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABE7OSFSDP2I4YMV42OPDF3WDEO5ZANCNFSM6AAAAAARERTOYE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-14 09:32 UTC, doterax commented on main.h
> +bool zopfli_lossy_transparent;
done

2022-10-14 09:34 UTC, JayXon approved these changes

2022-10-14 09:43 UTC, merged